# Generated by Django 4.2 on 2023-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
